### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by pyinto** [PookieBuns/fzf-sesh#1]
Hi! 
I want to map it to ctrl+K, so it works either in tmux and outside of the tmux. It's not a problem to map such action in tmux, but for zsh it's tricky:

```
call_fzf_sesh() {
  sh "$HOME/.config/.bin/fzf-sesh"
}

zle -N call_fzf_sesh
bindkey '^K' call_fzf_sesh
```
You need to create a widget in order to bind a script, I did so, and the window is popping up and creates a session you select, however it does not switches current context to it. Any ides of how to solve it? 

Great script btw, appreciate it!

**Comment by PookieBuns** [comment]
Hi. Thanks for the kind words!
In terms of your issue, the problem comes from zsh widgets with weird behavior how it doesn't actually use the current terminal or something (tbh I didn't really dive deep into it to figure out what it is [source](https://superuser.com/questions/835986/zsh-custom-widget-not-working-as-i-think-it-should))

Given this situation something you would want would probably be this taking inspiration from [source](https://gist.github.com/mooz/4175464)
```
call_fzf_sesh() {
  BUFFER="sh \"$HOME/.config/.bin/fzf-sesh\""
  zle accept-line
}

zle -N call_fzf_sesh
bindkey '^K' call_fzf_sesh
```
This basically sticks the command into your buffer and accepts it, simulating as if you typed out the command yourself

lmk if this does / does not work for you

**Comment by pyinto** [comment]
@PookieBuns awesome, thank you very much, that's the very thing I needed, everything works as I wanted!

```
call_fzf_sesh () {

  if [ -z "$TMUX" ]; then  # No TMUX session attached
    # Launching tmux inside a zle widget is tricky,
    # https://github.com/PookieBuns/fzf-sesh/issues/1
    BUFFER="sh \"$HOME/.config/.bin/fzf-sesh\""
    zle accept-line

  else  # TMUX session attached
    command "$HOME/.config/.bin/fzf-sesh"

  fi

}
zle -N call_fzf_sesh
bindkey "^U" "call_fzf_sesh"

```

**Comment by pyinto** [comment]
@PookieBuns btw, here is my layout for sesh based on your bin file

```
_fzf_sesh_fzf_sesh_list_tmux() {
    _fzf_sesh_list_with_icons | fzf-tmux \
    -p 55%,60% \
    --layout=reverse \
    --ansi \
    --no-sort \
    --border-label ' sesh ' \
    --prompt ' ⚡   ' \
    --header '      navigate:   ⌃t ⇒   ⌃g ⇒   ⌃x ⇒   ⌃A ⇒ ⚡︎ ⌃f ⇒     manage:   ⌃d ⇒ 󱄊  ⌃q ⇒ 󰚌  ' \
    --bind 'tab:down,btab:up' \
    --bind "ctrl-A:change-prompt( ⚡   )+reload($__fzf_sesh_list_with_icon_cmd)" \
    --bind "ctrl-t:change-prompt(     )+reload($__fzf_sesh_list_with_icon_cmd -t)" \
    --bind "ctrl-g:change-prompt(     ))+reload($__fzf_sesh_list_with_icon_cmd -c)" \
    --bind "ctrl-x:change-prompt(     )+reload($__fzf_sesh_list_with_icon_cmd -z)" \
    --bind "ctrl-f:change-prompt(     )+reload(fd -H -d 2 -t d -E .Trash . ~)" \
    --bind "ctrl-d:execute(tmux kill-session -t {2})+change-prompt( ⚡   )+reload($__fzf_sesh_list_with_icon_cmd)" \
    --bind "ctrl-q:execute(tmux kill-server)"
}

```
